name: Build & deploy
on:
    push:
        branches: [main]
    workflow_dispatch:
jobs:
    build:
        uses: keabyte/keabyte-workflows/.github/workflows/reactjs-build.yml@main
        secrets: inherit