name: main

on:
    push:
        branches: [main]
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.16.0]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm ci

            - name: Build Application
              run: npm run build

            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --delete
              env:
                  AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET_NAME }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_DEPLOYER_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_DEPLOYER_ACCESS_KEY_SECRET }}
                  SOURCE_DIR: 'dist'
